DROP ROLE IF EXISTS hummaps;
CREATE ROLE hummaps LOGIN NOINHERIT PASSWORD 'g712X$';
DROP DATABASE IF EXISTS production;
CREATE DATABASE production
  OWNER ubuntu
  ENCODING 'UTF8'
  TABLESPACE pg_default
  LC_COLLATE 'en_US.UTF-8'
  LC_CTYPE'en_US.UTF-8'
;
